apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample6-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample6-app
  template:
    metadata:
      labels:
        app: sample6-app
    spec:
      containers:
      - name: target1
        image: 235677655129.dkr.ecr.ap-northeast-1.amazonaws.com/eks-test-app:target1
        ports:
        - containerPort: 8080
