kind: Service
apiVersion: v1
metadata:
  name: sample-lb
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 30082
