kind: Service
apiVersion: v1
metadata:
  name: sample8-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=test1"
spec:
  type: LoadBalancer
  selector:
    app: sample8-app
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 30082
